### ISSUE TITLE
Would it be possible to show the changelog of what was added in the Update?

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/awgo#1]
When updating a workflow, it would be really nice to know what exactly was changed. Usually you add this change log to the release itself. However when updating, users just download the new workflow and that's it. 

Perhaps it would be nice to direct users and open the URL of the latest release when updating so they see what was changed?

**Comment by deanishe** [comment]
Personally, I hate it when apps open some webpage after I update them, so I'm not going to add it to the library.

If that's what you want your workflows to do, it's trivial to open the latest release URL when the user chooses the update action.

**Comment by nikitavoloboev** [comment]
Would it be possible to extract the name of the release and pop a notification after the Update was done? This usually contains the gist of what the release is about and doesn't annoyingly open a web page.

**Comment by deanishe** [comment]
No. The whole update API would need changing, as it's currently only concerned with version numbers, and there's no API for showing notifications.
