### ISSUE TITLE
Allow wf.Filter() to filter on subtitle 

### ISSUE THREAD

**Issue by TheSecEng** [deanishe/awgo#26]
It appears that `wf.Filter()` only filters on information in the `Title` which is nice, however it would be nice if we could filter based on subtitle text as well.

Is this something you'd consider?

**Comment by deanishe** [comment]
It falls back to filtering on on the title if you haven't [specified a string to filter against using `Match(s)`](https://godoc.org/github.com/deanishe/awgo#Item.Match).
