### ISSUE TITLE
Question: How to check if workflow is a rerun?

### ISSUE THREAD

**Issue by snipem** [deanishe/awgo#44]
Can I check if a run was invoked by Alfred by using `wf.Rerun()`?

**Comment by deanishe** [comment]
Alfred passes top-level variables back to your Script Filter on rerun, so you can set a variable, e.g. `Workflow.Var("is_rerun", "true")`, and check for its existence to tell whether your Script Filter is being rerun.

**Comment by snipem** [comment]
I'm trying to get and set it using this snippet, while setting seems to work I can't read the variable in the subsequent run. Do you have any clue?

```golang
// get
isRerun := vars.Vars()["is_rerun"]
// set
wf.Var("is_rerun", "true")
```

**Comment by deanishe** [comment]
> I can't read the variable in the subsequent run

Alfred sets workflow variables as environment variables. You need to read them from the environment with `os.Getenv()` or `Workflow.Config.GetBool()` etc.

`Workflow` doesn't import any environment variables: `Workflow.Vars()` only contains variables you've added with `Workflow.Var()` *during that run*.

If you need to load a whole bunch of environment variables, you can use `[Workflow.Config.To()`](https://godoc.org/github.com/deanishe/awgo#Config).
