### ISSUE TITLE
Question: what's the proper way to generate a workflow plist?

### ISSUE THREAD

**Issue by AllenDang** [deanishe/awgo#47]
This question is not an issue but a help request.
I'm new to alfred workflow development, so happy to see a golang kit, thanks for your work!

Is there any tool or suggested way to generate the plist of a workflow?

I checked it's content, seems there are few UUIDs need to generate. Should I just copy some existing plist from other workflow and change necessary fields by hand? Or there is a tool to auto-generate it for me?

**Comment by deanishe** [comment]
> Is there any tool or suggested way to generate the plist of a workflow?

Just use Alfred Preferences. The format is undocumented, and it's basically serialised application data.

AwGo has [a `build` subpackage with some tools to help with development](https://godoc.org/github.com/deanishe/awgo/util/build).

The way I do it is in [my build scripts](https://github.com/deanishe/alfred-gcal/blob/948147547d2d5074751d18120eecbbf3b2f3508e/magefile.go#L55), I build the binary in a `./build` subdirectory, and *symlink* all other assets to that directory, then symlink `./build` to Alfred's workflow directory. That way, I can edit info.plist in Alfred Preferences (via two symlinks) while keeping my repo where I want and structured the way I want.

The `Export()` function in `awgo/util` will resolve all the symlinks when creating an .alfredworkflow file from the `./build` directory.
