### ISSUE TITLE
go get error with go 1.14.1 on MacOS 10.15.5

### ISSUE THREAD

**Issue by AllenDang** [deanishe/awgo#48]
Run following cmd inside a go mod enabled project folder
go get -u github.com/deanishe/awgo

I got below error message

go: github.com/go-toolsmith/astp upgrade => v1.0.0
github.com/golangci/golangci-lint/pkg/golinters
../../../../../pkg/mod/github.com/golangci/golangci-lint@v1.28.1/pkg/golinters/gofumpt.go:49:41: cannot use "" (type string) as type format.Options in argument to format.Source

**Comment by deanishe** [comment]
Dunno what that's about. At any rate, I've removed the library-development deps from go.mod and released v0.24.1.

The issue appears to be fixed, though you might need to do `go get -u github.com/deanishe/awgo@v0.24.1`, as the Go proxy might still return the previous version.

**Comment by AllenDang** [comment]
@deanishe It is fixed even go get -u github.com/deanishe/awgo. Thanks!
