### ISSUE TITLE
Disable wf.Filter sorting

### ISSUE THREAD

**Issue by danielecook** [deanishe/awgo#5]
Is there a way to disable sorting but still filter results when using wf.Filter?

Thanks!

**Comment by deanishe** [comment]
Not using `wf.Filter`, no. You would have to use [`fuzzy.Match`](https://godoc.org/github.com/deanishe/awgo/fuzzy#Match) (or create a `fuzzy.Sorter` w/o data and use its `Match` method) to score each item and remove the non-matching ones yourself.

**Comment by danielecook** [comment]
Thanks I’ll dig a bit and see if I can figure it out
