### ISSUE TITLE
Split out `fuzzy` package as a separate repo

### ISSUE THREAD

**Issue by zikaeroh** [deanishe/awgo#51]
I'm using your great `fuzzy` package to do some sorting in one of my projects, but I'm not using the rest of the codebase. Is there any chance you'd split out the `fuzzy` package to its own repo/module so it can be consumed independently?

**Comment by deanishe** [comment]
I suppose I could if there's demand for it.

But you already should be able to import and use it, as I built it to work independently of the rest of the library.

**Comment by zikaeroh** [comment]
Oh, certainly. That's what I do now. It being in this repo just means I see a bit of update churn from releases that don't change the `fuzzy` package (it hasn't been touched in 10 months) and that I have a few extra dependencies to download (since you depend on a module, not a package). This isn't the highest priority request. :slightly_smiling_face:

**Comment by deanishe** [comment]
Okay, I've extracted the `fuzzy` package. It's importable as `go.deanishe.net/fuzzy`, and [hosted on GitHub](https://github.com/deanishe/go-fuzzy).

I fixed a long-standing bug that wasn't apparent from its use in AwGo, and it should also be a tiny bit faster now, too.

**Comment by zikaeroh** [comment]
Wonderful, thank you!
